#!/bin/bash

echo ""
echo ""
echo "     _.-^^---....,,--        "
echo " _--                  --_    "
echo " <                        >) "
echo " |                         | "
echo "  \._                   _./  "
echo "     '''--. . , ; .--'''     "
echo "          | |   |            "
echo "       .-=||  | |=-.         "
echo "        -=#$%&%$#=-'         "
echo "          | ;  :|            "
echo "      .,-#%&$@%#&#~,         "
echo "  -------------------------  "
echo "  NUKING YOUR SAITO INSTALL  "
echo "  -------------------------  "
echo ""

find src/data/blocks -name '*.sai' | xargs rm -r