name: Rust Docs

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create
        run: cargo doc --no-deps

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/doc # The folder the action should deploy.