name: Tests

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

jobs:
  tests:
    name: Test Suite
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        toolchain: [ 'stable', '1.53.0', '1.56.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: debug
          RUSTFLAGS: "-D warnings"
        with:
          command: test
          args: -- --verbose
